---
services:
  php_alchemist.event.listener.liable:
    class: PHPAlchemist\DoctrineBehaviors\Event\Listener\LiableEventListener
    autowire: true
    autoconfigure: true
    tags:
       - {
        name: doctrine.event_listener
        event:
          - 'prePersist'
          - 'preUpdate'
          - 'preRemove'
        priority: 500
        connection: default
        arguments:
             $security: '@Symfony\Bundle\SecurityBundle\Security'
          }

  php_alchemist.event.listener.timestampable:
    class: PHPAlchemist\DoctrineBehaviors\Event\Listener\TimestampableEventListener
    autowire: true
    autoconfigure: true
    tags:
       - {
        name: doctrine.event_listener
        event:
          - 'prePersist'
          - 'preUpdate'
        priority: 500
        connection: default
        arguments:
             $security: '@Symfony\Bundle\SecurityBundle\Security'
       }

  php_alchemist.event.listener.soft_deleteable:
    class: PHPAlchemist\DoctrineBehaviors\Event\Listener\SoftDeleteableListener
    autowire: true
    autoconfigure: true
    tags:
       - {
        name: doctrine.event_listener
        event:
          - 'onFlush'
        priority: 500
        connection: default
        arguments:
             $security: '@Symfony\Bundle\SecurityBundle\Security'
       }
